name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          
          # Extract version components
          major=$(echo $latest_tag | cut -d. -f1 | tr -d 'v')
          minor=$(echo $latest_tag | cut -d. -f2)
          patch=$(echo $latest_tag | cut -d. -f3)
          
          # Increment minor version for new release
          new_minor=$((minor + 1))
          new_tag="v$major.$new_minor.0"
          
          # Create new tag
          git tag $new_tag
          
          # Push the tag
          git push origin $new_tag
          
          # Create GitHub release
          gh release create $new_tag \
            --title "Release $new_tag" \
            --notes "$(git log $latest_tag..HEAD --pretty=format:'- %s')" 